site_name: 时清川的课程笔记
site_url: https://sqc-cyh.github.io/
site_author: 时清川
theme:
  name: material #主题
  custom_dir: overrides
  favicon: images/favicon.png
  palette:
   # Palette toggle for light mode
    - scheme: index_light
      # primary: index
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
 
    # Palette toggle for dark mode
    - scheme: index_night
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features: 
    - content.code.annotate
    - content.code.copy
    # - navigation.instant # This will cause LaTeX render fail at the first try.
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share

  icon: 
    repo: fontawesome/brands/github #右上角图标
edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/sqc-cyh # 右上角点击跳转的链接
repo_name: sqc-cyh.github.io # 右上角的名字

#目录
nav:
  - "首页": 
    - "家": index.md
  - "课程笔记":
    - "⭐数据库系统": 
      - lessons/D2CX_DatabaseSystem/index.md
      - lessons/D2CX_DatabaseSystem/Chap01.md
    - "⭐高级数据结构与算法分析":
      - lessons/D2CX_AdvancedDataStructure/index.md
      - lessons/D2CX_AdvancedDataStructure/Chap01.md
      # - 第一章: lessons/高级数据结构与算法分析.md
      # - 第二章: lessons/高级数据结构与算法分析.md
  - 科研相关:
    - 好玩2: home/home.md
  - 技能树:
    - 好玩3: home/home.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sqc-cyh
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1076219827@qq.com> #联系方式
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - search
  - tags
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等



  

