site_name: 时清川的个人主页
site_url: https://sqc-cyh.github.io/
site_author: 时清川
theme:
  name: material #主题
  custom_dir: overrides
  favicon: images/favicon.png
  # titles_only: true
  palette:
   # Palette toggle for light mode
    - scheme: index_light
      # primary: index
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
 
    # Palette toggle for dark mode
    - scheme: index_night
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features: 
    # - navigation.instant   #- header.autohide  #自动隐藏
    #- announce.dismiss   #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking   #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs   #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    #- navigation.tabs.sticky    #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    # - navigation.sections   #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top   # 返回顶部的按钮 在上滑时出现
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlight   # 搜索出的文章关键词加入高亮
    # - navigation.expand   # 打开Tab时左侧目录全部展开
    - navigation.indexes   #启用节索引页后，可以将文档直接附加到节
    # - navigation.sections
    - search.share   #搜索分享按钮
    - content.code.annotate #代码注释
    - content.code.copy

  icon: 
    repo: fontawesome/brands/github #右上角图标
edit_uri: edit/main/docs # 编辑按钮跳转的链接 
repo_url: https://github.com/sqc-cyh # 右上角点击跳转的链接
repo_name: sqc-cyh.github.io # 右上角的名字

#目录
nav:
  - "家": 
    - "家": index.md
  - "课程笔记":
    - LessonsNotes/index.md
    - "⭐数据库系统": 
      - LessonsNotes/D2CX_DatabaseSystem/index.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap01.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap02.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap03.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap04.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap05.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap06.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap07.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap08.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap09.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap10.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap11.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap12.md
      - LessonsNotes/D2CX_DatabaseSystem/Chap13.md
    - "⭐高级数据结构与算法分析":
      - LessonsNotes/D2CX_AdvancedDataStructure/index.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap01.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap02.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap03.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap04.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap05.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap06.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap07.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap08.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap09.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap10.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap11.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap12.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap13.md
      - LessonsNotes/D2CX_AdvancedDataStructure/Chap14.md
      # - 第一章: lessons/高级数据结构与算法分析.md
      # - 第二章: lessons/高级数据结构与算法分析.md
    - "⭐信息安全原理":
      - LessonsNotes/D2CX_Xinanyuan/note.md
    - "⭐深度学习":  
      - LessonsNotes/DXQ_DeepLearning/index.md
      - LessonsNotes/DXQ_DeepLearning/note.md
  - 科研相关:
    - 好玩2: home/home.md
  - "技能树":
    - SkillTree/index.md
    - "⭐如何搭建一个个人网页":
      - SkillTree/MakeYourOwnWeb/index.md
    - "⭐MarkDown语法教程":
      - SkillTree/MarkDown/index.md
    - "⭐机器学习":
      - SkillTree/MachineLearning/index.md
      - SkillTree/MachineLearning/Chap01.md
      - SkillTree/MachineLearning/Chap02.md
  - "诗":
    - "Poems/index.md"
    - "Poems/风吹的夜.md"
  - "友链":
    - "Friends/index.md"
extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sqc-cyh
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1076219827@qq.com> #联系方式
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://fonts.loli.net/css2?family=Noto+Serif+SC&display=swap
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
plugins:
  - search
  - tags
  - statistics:
      words_per_minute: 200
markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - def_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等



  

